#!/usr/bin/perl
# rapio
use strict;

my $stationsFile = "$ENV{HOME}/.config/rapio/channels";
my $command = "mplayer -cache 100";

my %radioStations;
open(my $fh, '<', $stationsFile) or die "Cant open $stationsFile: $!";
while(<$fh>) {
  chomp;
  my ($name,$url) = split/\s+/;
  $radioStations{$name} .= exists $radioStations{$name} ? "$url" : $url;
}
close $stationsFile;

my $choice = shift;
if(!$choice) {
  usage();
  print "Station: ";
  $choice = <STDIN>;
  chomp($choice);
}
system("$command $radioStations{$choice}") or die;

sub usage {
  print << "USAGE";
  USAGE
    $0 <station>

USAGE

  foreach my $name(sort(keys(%radioStations))) {
    printf("%20s %s\n", $name, $radioStations{$name});
  }
}
