#!/usr/bin/perl
use strict;
use vars($VERSION);
$VERSION = '1.002';

use Daemon::Mplayer qw(mplayer_play mplayer_stop);

if($ARGV[0] =~ m{-?-?k(?:ill)?}) {
  mplayer_stop(
    {
      pidfile => '/tmp/rapio.pid',
    }
  );
  exit;
}


my $stations = do {
  -f "$ENV{HOME}/.local/share/rapio/channels"
    ? "$ENV{HOME}/.local/share/rapio/channels"
    : -f './channels'
      ? './channels'
      : die("No channel file found!\n");
};


open(my $fh, '<', $stations) or die("Cant open $stations: $!\n");

my %channels = ();
while(my $r = <$fh>) {
  chomp($r);
  my($name, $url) = split(/\s+/, $r);
  $name = lc($name);
  $channels{$name} .= exists($channels{ $name }) ? "$url" : $url;
}

for my $s(sort(keys(%channels))) {
  printf("%s\n", $s);
}

print "> ";
chomp(my $choice = <>);

if(exists( $channels{ $choice } )) {

  mplayer_play(
    {
      pidfile => '/tmp/rapio.pid',
      logfile => '/dev/null',
      path    => '/usr/bin/mplayer',
      args    => [ qw(-cache 200), $channels{ $choice } ],
    }
  );
}
else {
  die("No such channel '$choice'\n");
}
